# Use the official Node.js image.
# https://hub.docker.com/_/node
FROM node:20 as production

# Create and change to the app directory.
WORKDIR /src/app

# Copy application dependency manifest  s to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install dependencies.
RUN yarn install

# Copy local code to the container image.
COPY . .

# Run the web service on container startup.
CMD [ "yarn", "start" ]

# Inform Docker that the container listens on the specified port at runtime.
EXPOSE 3040